// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDiscard() {
  return window['go']['main']['App']['ConfirmDiscard']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenDialog() {
  return window['go']['main']['App']['OpenDialog']();
}

export function ReadDocument(arg1) {
  return window['go']['main']['App']['ReadDocument'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDialog(arg1) {
  return window['go']['main']['App']['SaveDialog'](arg1);
}

export function WriteDocument(arg1, arg2) {
  return window['go']['main']['App']['WriteDocument'](arg1, arg2);
}
