// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig():Promise<string>;

export function LoadDocument():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveDocument(arg1:string):Promise<void>;
