// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDiscard():Promise<boolean>;

export function LoadConfig():Promise<string>;

export function OpenDialog():Promise<string>;

export function ReadDocument(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveDialog(arg1:string):Promise<string>;

export function WriteDocument(arg1:string,arg2:string):Promise<void>;
