// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadDocument():Promise<string>;

export function SaveDocument(arg1:string):Promise<void>;
